// Milestones selected from the manuscript's clickable evolution tree.
// Project links are matched to the repository README; existing paper/code fallbacks are retained.
export type Branch = "root" | "robotics" | "embodied" | "digital";
export type TreeNode = {
  id: string;
  title: string;
  year: number;
  branch: Branch;
  kind: "System" | "Model" | "Benchmark";
  detail: string;
  url?: string;
  linkLabel?: string;
};
export const nodes: TreeNode[] = [
  {
    id: "root",
    title: "Embodied agency",
    year: 2017,
    branch: "root",
    kind: "System",
    detail:
      "The shared root: agents sensing, deciding, and intervening in an environment.",
  },
  {
    id: "dvf",
    url: "https://sites.google.com/site/robotforesight/",
    linkLabel: "Project page",
    title: "Visual Foresight",
    year: 2017,
    branch: "robotics",
    kind: "Model",
    detail:
      "Visual prediction supports action selection for robotic manipulation.",
  },
  {
    id: "dexnet",
    url: "https://berkeleyautomation.github.io/dex-net/",
    linkLabel: "Project page",
    title: "Dex-Net 2.0",
    year: 2017,
    branch: "robotics",
    kind: "Model",
    detail:
      "Synthetic grasp data connects perception to robust physical control.",
  },
  {
    id: "r2r",
    url: "https://bringmeaspoon.org",
    linkLabel: "Project page",
    title: "R2R-VLN",
    year: 2018,
    branch: "robotics",
    kind: "Benchmark",
    detail:
      "Language-guided navigation links semantic goals to embodied trajectories.",
  },
  {
    id: "alfred",
    url: "https://askforalfred.com/",
    linkLabel: "Project page",
    title: "ALFRED",
    year: 2020,
    branch: "robotics",
    kind: "Benchmark",
    detail:
      "Long-horizon household tasks connect language, vision, and action.",
  },
  {
    id: "kimera",
    url: "https://github.com/MIT-SPARK/Kimera",
    linkLabel: "Code repository",
    title: "Kimera",
    year: 2020,
    branch: "robotics",
    kind: "System",
    detail:
      "Persistent spatial and semantic representations ground embodied perception.",
  },
  {
    id: "saycan",
    url: "https://say-can.github.io/",
    linkLabel: "Project page",
    title: "SayCan",
    year: 2022,
    branch: "embodied",
    kind: "System",
    detail:
      "Language-model proposals are grounded through learned robotic affordances.",
  },
  {
    id: "inner",
    url: "https://innermonologue.github.io",
    linkLabel: "Project page",
    title: "Inner Monologue",
    year: 2022,
    branch: "embodied",
    kind: "System",
    detail: "Scene feedback and success signals close the planning loop.",
  },
  {
    id: "rt2",
    url: "https://robotics-transformer2.github.io/",
    linkLabel: "Project page",
    title: "RT-2",
    year: 2023,
    branch: "robotics",
    kind: "Model",
    detail:
      "Vision-language knowledge transfers into generalizable robotic control.",
  },
  {
    id: "palme",
    url: "https://palm-e.github.io/",
    linkLabel: "Project page",
    title: "PaLM-E",
    year: 2023,
    branch: "embodied",
    kind: "Model",
    detail:
      "Embodied multimodal representations connect language and sensor streams.",
  },
  {
    id: "reflect",
    url: "https://robot-reflect.github.io/",
    linkLabel: "Project page",
    title: "REFLECT",
    year: 2023,
    branch: "embodied",
    kind: "System",
    detail: "Failure explanation and correction make verification operational.",
  },
  {
    id: "avis",
    url: "https://arxiv.org/abs/2306.08129",
    linkLabel: "Paper",
    title: "AVIS",
    year: 2023,
    branch: "digital",
    kind: "System",
    detail: "Adaptive tool use turns information seeking into a decision loop.",
  },
  {
    id: "mmreact",
    url: "https://multimodal-react.github.io/",
    linkLabel: "Project page",
    title: "MM-REACT",
    year: 2023,
    branch: "digital",
    kind: "System",
    detail:
      "Multimodal reasoning coordinates specialist tools in digital environments.",
  },
  {
    id: "robodreamer",
    url: "https://robovideo.github.io/",
    linkLabel: "Project page",
    title: "RoboDreamer",
    year: 2024,
    branch: "robotics",
    kind: "Model",
    detail:
      "World-model imagination supports robotic planning before execution.",
  },
  {
    id: "aha",
    url: "https://aha-vlm.github.io/",
    linkLabel: "Project page",
    title: "AHA",
    year: 2024,
    branch: "embodied",
    kind: "Benchmark",
    detail: "Embodied evaluation exposes hallucination and recovery behavior.",
  },
  {
    id: "rekep",
    url: "https://rekep-robot.github.io/",
    linkLabel: "Project page",
    title: "ReKep",
    year: 2024,
    branch: "embodied",
    kind: "System",
    detail:
      "Relational keypoint constraints structure long-horizon manipulation.",
  },
  {
    id: "visualwebarena",
    url: "https://jykoh.com/vwa",
    linkLabel: "Project page",
    title: "VisualWebArena",
    year: 2024,
    branch: "digital",
    kind: "Benchmark",
    detail:
      "Visual web tasks expose grounded reasoning over realistic interfaces.",
  },
  {
    id: "osworld",
    url: "https://os-world.github.io/",
    linkLabel: "Project page",
    title: "OSWorld",
    year: 2024,
    branch: "digital",
    kind: "Benchmark",
    detail:
      "Computer-use agents are evaluated against observable application state.",
  },
  {
    id: "roboarena",
    url: "https://robo-arena.github.io/",
    linkLabel: "Project page",
    title: "RoboArena",
    year: 2025,
    branch: "robotics",
    kind: "Benchmark",
    detail:
      "Real-world evaluation adds environmental and execution variability.",
  },
  {
    id: "reflective",
    url: "https://reflect-vlm.github.io",
    linkLabel: "Project page",
    title: "Reflective Planning",
    year: 2025,
    branch: "embodied",
    kind: "System",
    detail: "Reflection links planning decisions to feedback and correction.",
  },
  {
    id: "gemini",
    url: "https://deepmind.google/en/models/gemini-robotics/gemini-robotics/",
    linkLabel: "Project page",
    title: "Gemini Robotics 1.5",
    year: 2025,
    branch: "embodied",
    kind: "System",
    detail: "Generalist multimodal reasoning and physical action converge.",
  },
  {
    id: "agents2",
    url: "https://www.simular.ai/articles/agent-s2-technical-review",
    linkLabel: "Project page",
    title: "Agent S2",
    year: 2025,
    branch: "digital",
    kind: "System",
    detail:
      "Specialized agents coordinate perception, planning, and GUI interaction.",
  },
  {
    id: "showui",
    url: "https://github.com/showlab/ShowUI",
    linkLabel: "Code repository",
    title: "ShowUI",
    year: 2025,
    branch: "digital",
    kind: "Model",
    detail:
      "Vision-language-action modeling advances generalist GUI interaction.",
  },
  {
    id: "metaworlds",
    url: "https://metaworld.farama.org/",
    linkLabel: "Project page",
    title: "Meta-World+",
    year: 2026,
    branch: "robotics",
    kind: "Benchmark",
    detail: "A current benchmark frontier for evaluating robotic interaction.",
  },
  {
    id: "robolab",
    url: "https://research.nvidia.com/labs/srl/projects/robolab/",
    linkLabel: "Project page",
    title: "RoboLab",
    year: 2026,
    branch: "robotics",
    kind: "Benchmark",
    detail: "An integrated platform for studying capable robotic agents.",
  },
  {
    id: "recursive",
    url: "https://arxiv.org/abs/2602.20659",
    linkLabel: "Paper",
    title: "RB-VLA",
    year: 2026,
    branch: "embodied",
    kind: "Model",
    detail:
      "Recursive belief updates connect observation, action, and task progress.",
  },
  {
    id: "wla",
    url: "https://github.com/SJTU-DENG-Lab/WLA",
    linkLabel: "Code repository",
    title: "World-Lang-Action",
    year: 2026,
    branch: "embodied",
    kind: "Model",
    detail:
      "World modeling and language reasoning are coupled to physical action.",
  },
  {
    id: "adapt",
    url: "https://charlotteannchen.github.io/ADAPT/",
    linkLabel: "Project page",
    title: "ADAPT",
    year: 2026,
    branch: "embodied",
    kind: "Benchmark",
    detail:
      "Commonsense planning is evaluated under unspecified affordance constraints.",
  },
  {
    id: "osworld2",
    url: "https://osworld-v2.xlang.ai/",
    linkLabel: "Project page",
    title: "OSWorld 2.0",
    year: 2026,
    branch: "digital",
    kind: "Benchmark",
    detail: "Broader operating-system tasks stress generalist digital agents.",
  },
  {
    id: "code2world",
    url: "https://amap-ml.github.io/Code2World/",
    linkLabel: "Project page",
    title: "Code2World",
    year: 2026,
    branch: "digital",
    kind: "Model",
    detail:
      "Executable world representations support prospective digital interaction.",
  },
  {
    id: "nasiriany2026robocasa365",
    title: "RoboCasa365",
    year: 2026,
    branch: "robotics",
    url: "https://robocasa.ai/",
    linkLabel: "Project page",
    detail:
      "RoboCasa365: A Large-Scale Simulation Framework for Training and Benchmarking Generalist Robots",
    kind: "Benchmark",
  },
  {
    id: "zhang2026assistance",
    title: "NIABench",
    year: 2026,
    branch: "robotics",
    url: "https://renytek13.github.io/assistance-without-interruption/",
    linkLabel: "Project page",
    detail:
      "Assistance Without Interruption: A Benchmark and LLM-based Framework for Non-Intrusive Human-Robot Assistance",
    kind: "Benchmark",
  },
  {
    id: "activevla2026",
    title: "ActiveVLA",
    year: 2026,
    branch: "robotics",
    url: "https://zhenyangliu.github.io/ActiveVLA/",
    linkLabel: "Project page",
    detail:
      "ActiveVLA: Injecting Active Perception into Vision-Language-Action Models for Precise 3D Robotic Manipulation",
    kind: "System",
  },
  {
    id: "jiang2026robowm",
    title: "RoboWM-Bench",
    year: 2026,
    branch: "robotics",
    url: "https://robowm-bench.github.io/RoboWM-Bench/",
    linkLabel: "Project page",
    detail:
      "RoboWM-Bench: A Benchmark for Evaluating World Models in Robotic Manipulation",
    kind: "Benchmark",
  },
  {
    id: "huang2026vla",
    title: "VLA-REPLICA",
    year: 2026,
    branch: "robotics",
    url: "https://irvlutd.github.io/VLAReplica/",
    linkLabel: "Project page",
    detail:
      "VLA-REPLICA: A Low-Cost, Reproducible Benchmark for Real-World Evaluation of Vision-Language-Action Models",
    kind: "Benchmark",
  },
  {
    id: "xvla2026",
    title: "X-VLA",
    year: 2026,
    branch: "robotics",
    url: "https://thu-air-dream.github.io/X-VLA/",
    linkLabel: "Project page",
    detail:
      "X-VLA: Soft-Prompted Transformer as Scalable Cross-Embodiment Vision-Language-Action Model",
    kind: "System",
  },
  {
    id: "zhou2025libero",
    title: "LIBERO-PRO",
    year: 2025,
    branch: "robotics",
    url: "https://zxy-mllab.github.io/LIBERO-PRO-Webpage/",
    linkLabel: "Project page",
    detail:
      "LIBERO-PRO: Towards Robust and Fair Evaluation of Vision-Language-Action Models Beyond Memorization",
    kind: "Benchmark",
  },
  {
    id: "jiang2025behavior",
    title: "BEHAVIOR Suite",
    year: 2025,
    branch: "robotics",
    url: "https://behavior-robot-suite.github.io/",
    linkLabel: "Project page",
    detail:
      "BEHAVIOR Robot Suite: Streamlining Real-World Whole-Body Manipulation for Everyday Household Activities",
    kind: "System",
  },
  {
    id: "robochallenge2025",
    title: "RoboChallenge",
    year: 2025,
    branch: "robotics",
    url: "https://robochallenge.ai/home",
    linkLabel: "Project page",
    detail:
      "RoboChallenge: Large-scale Real-robot Evaluation of Embodied Policies",
    kind: "Benchmark",
  },
  {
    id: "chen2025robotwin",
    title: "RoboTwin 2.0",
    year: 2025,
    branch: "robotics",
    url: "https://robotwin-platform.github.io/",
    linkLabel: "Project page",
    detail:
      "RoboTwin 2.0: A Scalable Data Generator and Benchmark with Strong Domain Randomization for Robust Bimanual Robotic Manipulation",
    kind: "Benchmark",
  },
  {
    id: "jangir2025robotarena",
    title: "RobotArena∞",
    year: 2025,
    branch: "robotics",
    url: "https://robotarenainf.github.io/",
    linkLabel: "Project page",
    detail:
      "RobotArena ∞: Scalable Robot Benchmarking via Real-to-Sim Translation",
    kind: "Benchmark",
  },
  {
    id: "hu2024video",
    title: "Video Pred. Policy",
    year: 2024,
    branch: "robotics",
    url: "https://video-prediction-policy.github.io",
    linkLabel: "Project page",
    detail:
      "Video Prediction Policy: A Generalist Robot Policy with Predictive Visual Representations",
    kind: "System",
  },
  {
    id: "octo2024",
    title: "Octo",
    year: 2024,
    branch: "robotics",
    url: "https://octo-models.github.io",
    linkLabel: "Project page",
    detail: "Octo: An Open-Source Generalist Robot Policy",
    kind: "System",
  },
  {
    id: "wang2024hpt",
    title: "HPT",
    year: 2024,
    branch: "robotics",
    url: "https://liruiw.github.io/hpt",
    linkLabel: "Project page",
    detail:
      "Scaling Proprioceptive-Visual Learning with Heterogeneous Pre-trained Transformers",
    kind: "System",
  },
  {
    id: "worldvlaloop2026",
    title: "World-VLA-Loop",
    year: 2026,
    branch: "embodied",
    url: "https://showlab.github.io/World-VLA-Loop/",
    linkLabel: "Project page",
    detail:
      "World-VLA-Loop: Closed-Loop Learning of Video World Model and VLA Policy",
    kind: "System",
  },
  {
    id: "hong2026esi",
    title: "ESI-Bench",
    year: 2026,
    branch: "embodied",
    url: "https://esi-bench.github.io/",
    linkLabel: "Project page",
    detail:
      "ESI-Bench: Towards Embodied Spatial Intelligence that Closes the Perception-Action Loop",
    kind: "System",
  },
  {
    id: "guo2026planar",
    title: "PlanAR",
    year: 2026,
    branch: "embodied",
    url: "https://planar-robot.github.io/",
    linkLabel: "Project page",
    detail:
      "PLanAR: Planning-Language-Grounded Agentic Reasoning for Robot Manipulation",
    kind: "System",
  },
  {
    id: "fu2026cap",
    title: "CaP-X",
    year: 2026,
    branch: "embodied",
    url: "https://capgym.github.io/",
    linkLabel: "Project page",
    detail:
      "CaP-X: A Framework for Benchmarking and Improving Coding Agents for Robot Manipulation",
    kind: "Benchmark",
  },
  {
    id: "han2026robocerebra",
    title: "RoboCerebra",
    year: 2026,
    branch: "embodied",
    url: "https://robocerebra.github.io/",
    linkLabel: "Project page",
    detail:
      "RoboCerebra: A Large-scale Benchmark for Long-horizon Robotic Manipulation Evaluation",
    kind: "Benchmark",
  },
  {
    id: "yang2025embodiedbench",
    title: "EmbodiedBench",
    year: 2025,
    branch: "embodied",
    url: "https://embodiedbench.github.io/",
    linkLabel: "Project page",
    detail:
      "EMBODIEDBENCH: Comprehensive Benchmarking Multi-modal Large Language Models for Vision-Driven Embodied Agents",
    kind: "Benchmark",
  },
  {
    id: "evolvevla2025",
    title: "EVOLVE-VLA",
    year: 2025,
    branch: "embodied",
    url: "https://showlab.github.io/EVOLVE-VLA",
    linkLabel: "Project page",
    detail:
      "EVOLVE-VLA: Test-Time Training from Environment Feedback for Vision-Language-Action Models",
    kind: "System",
  },
  {
    id: "chen2025emos",
    title: "EMOS",
    year: 2025,
    branch: "embodied",
    url: "https://emos-project.github.io/",
    linkLabel: "Project page",
    detail:
      "EMOS: Embodiment-aware Heterogeneous Multi-robot Operating System with LLM Agents",
    kind: "System",
  },
  {
    id: "chang2025partnr",
    title: "PARTNR",
    year: 2025,
    branch: "embodied",
    url: "https://aihabitat.org/partnr/",
    linkLabel: "Project page",
    detail:
      "PARTNR: A Benchmark for Planning and Reasoning in Embodied Multi-agent Tasks",
    kind: "Benchmark",
  },
  {
    id: "mandi2024roco",
    title: "RoCo",
    year: 2024,
    branch: "embodied",
    url: "https://project-roco.github.io/",
    linkLabel: "Project page",
    detail:
      "RoCo: Dialectic Multi-Robot Collaboration with Large Language Models",
    kind: "System",
  },
  {
    id: "exploreconfident2024",
    title: "Explore until Confident",
    year: 2024,
    branch: "embodied",
    url: "https://explore-eqa.github.io",
    linkLabel: "Project page",
    detail:
      "Explore until Confident: Efficient Exploration for Embodied Question Answering",
    kind: "System",
  },
  {
    id: "guo2024doremi",
    title: "DoReMi",
    year: 2024,
    branch: "embodied",
    url: "https://sites.google.com/view/doremi-paper",
    linkLabel: "Project page",
    detail:
      "DoReMi: Grounding Language Model by Detecting and Recovering from Plan-Execution Misalignment",
    kind: "System",
  },
  {
    id: "huang2023voxposer",
    title: "VoxPoser",
    year: 2023,
    branch: "embodied",
    url: "https://voxposer.github.io/",
    linkLabel: "Project page",
    detail:
      "VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models",
    kind: "System",
  },
  {
    id: "tao2026mmsearch",
    title: "MMSearch-Plus",
    year: 2026,
    branch: "digital",
    url: "https://mmsearch-plus.github.io/",
    linkLabel: "Project page",
    detail:
      "MMSearch-Plus: Benchmarking Provenance-Aware Search for Multimodal Browsing Agents",
    kind: "Benchmark",
  },
  {
    id: "fu2026video",
    title: "Video-MME-v2",
    year: 2026,
    branch: "digital",
    url: "https://video-mme-v2.netlify.app/",
    linkLabel: "Project page",
    detail:
      "Video-MME-v2: Towards the Next Stage in Benchmarks for Comprehensive Video Understanding",
    kind: "Benchmark",
  },
  {
    id: "su2026agentvista",
    title: "AgentVista",
    year: 2026,
    branch: "digital",
    url: "https://agentvista-bench.github.io/",
    linkLabel: "Project page",
    detail:
      "AgentVista: Evaluating Multimodal Agents in Ultra-Challenging Realistic Visual Scenarios",
    kind: "System",
  },
  {
    id: "ouyang2026gameworld",
    title: "GameWorld",
    year: 2026,
    branch: "digital",
    url: "https://gameworld-project.github.io/",
    linkLabel: "Project page",
    detail:
      "GameWorld: Towards Standardized and Verifiable Evaluation of Multimodal Game Agents",
    kind: "Benchmark",
  },
  {
    id: "luo2026gamecraft",
    title: "GameCraft-Bench",
    year: 2026,
    branch: "digital",
    url: "https://tongxuluo.github.io/gamecraft-bench-website/",
    linkLabel: "Project page",
    detail:
      "GameCraft-Bench: Can Agents Build Playable Games End-to-End in a Real Game Engine?",
    kind: "System",
  },
  {
    id: "li2026worldmodelbench",
    title: "WorldModelBench",
    year: 2026,
    branch: "digital",
    url: "https://worldmodelbench-team.github.io/",
    linkLabel: "Project page",
    detail: "WorldModelBench: Judging Video Generation Models As World Models",
    kind: "System",
  },
  {
    id: "wu2025osatlas",
    title: "OS-ATLAS",
    year: 2024,
    branch: "digital",
    url: "https://osatlas.github.io/",
    linkLabel: "Project page",
    detail: "OS-ATLAS: A Foundation Action Model for Generalist GUI Agents",
    kind: "System",
  },
  {
    id: "rawles2025androidworld",
    title: "AndroidWorld",
    year: 2025,
    branch: "digital",
    url: "https://google-research.github.io/android_world/",
    linkLabel: "Project page",
    detail:
      "AndroidWorld: A Dynamic Benchmarking Environment for Autonomous Agents",
    kind: "Benchmark",
  },
  {
    id: "yue2025mmmu",
    title: "MMMU-Pro",
    year: 2025,
    branch: "digital",
    url: "https://mmmu-benchmark.github.io/",
    linkLabel: "Project page",
    detail:
      "MMMU-Pro: A More Robust Multi-discipline Multimodal Understanding Benchmark",
    kind: "Benchmark",
  },
  {
    id: "tian2025mmina",
    title: "MMInA",
    year: 2025,
    branch: "digital",
    url: "https://mmina.cliangyu.com/",
    linkLabel: "Project page",
    detail: "MMInA: Benchmarking Multihop Multimodal Internet Agents",
    kind: "Benchmark",
  },
  {
    id: "zheng2025agentstudio",
    title: "AgentStudio",
    year: 2025,
    branch: "digital",
    url: "https://ltzheng.github.io/agent-studio/",
    linkLabel: "Project page",
    detail: "AgentStudio: A Toolkit for Building General Virtual Agents",
    kind: "System",
  },
  {
    id: "xu2025crab",
    title: "CRAB",
    year: 2025,
    branch: "digital",
    url: "https://crab.camel-ai.org/",
    linkLabel: "Project page",
    detail:
      "CRAB: Cross-environment Agent Benchmark for Multimodal Language Model Agents",
    kind: "Benchmark",
  },
  {
    id: "mayer2025ivispar",
    title: "iVISPAR",
    year: 2025,
    branch: "digital",
    url: "https://microcosm.ai/ivispar/",
    linkLabel: "Project page",
    detail:
      "iVISPAR -- An Interactive Visual-Spatial Reasoning Benchmark for VLMs",
    kind: "Benchmark",
  },
  {
    id: "nvidia2025pbench",
    title: "PBench",
    year: 2025,
    branch: "digital",
    url: "https://research.nvidia.com/labs/cosmos-lab/pbench/",
    linkLabel: "Project page",
    detail: "PBench: A Physical AI Benchmark for World Models",
    kind: "Benchmark",
  },
  {
    id: "liu2024llava",
    title: "LLaVA-Plus",
    year: 2024,
    branch: "digital",
    url: "https://llava-vl.github.io/llava-plus/",
    linkLabel: "Project page",
    detail: "LLaVA-Plus: Learning to Use Tools for Creating Multimodal Agents",
    kind: "System",
  },
  {
    id: "showuipi2026",
    title: "ShowUI-π",
    year: 2026,
    branch: "digital",
    url: "https://showlab.github.io/showui-pi",
    linkLabel: "Project page",
    detail: "ShowUI-π: Flow-based Generative Models as GUI Dexterous Hands",
    kind: "System",
  },
  {
    id: "chen2026showharness",
    title: "Show-Harness",
    year: 2026,
    branch: "embodied",
    kind: "System",
    detail: "Show-Harness",
    url: "https://showlab.github.io/Show-Harness/",
    linkLabel: "Project page",
  },
  {
    id: "black2024pi0",
    title: "π₀",
    year: 2024,
    branch: "robotics",
    kind: "Model",
    detail: "π₀: A Vision-Language-Action Flow Model for General Robot Control",
    url: "https://www.pi.website/blog/pi0",
    linkLabel: "Project page",
  },
  {
    id: "liu2024okrobot",
    title: "OK-Robot",
    year: 2024,
    branch: "robotics",
    kind: "System",
    detail:
      "OK-Robot: What Really Matters in Integrating Open-Knowledge Models for Robotics",
    url: "https://ok-robot.github.io/",
    linkLabel: "Project page",
  },
  {
    id: "codeasmonitor2024",
    title: "Code-as-Monitor",
    year: 2025,
    branch: "embodied",
    kind: "System",
    detail:
      "Code-as-Monitor: Constraint-aware Visual Programming for Reactive and Proactive Robotic Failure Detection (CVPR 2025)",
    url: "https://zhoues.github.io/Code-as-Monitor/",
    linkLabel: "Project page",
  },
  {
    id: "fastinslow2025",
    title: "Fast-in-Slow",
    year: 2025,
    branch: "embodied",
    kind: "Model",
    detail:
      "Fast-in-Slow: A Dual-System Foundation Model Unifying Fast Manipulation within Slow Reasoning",
    url: "https://fast-in-slow.github.io/",
    linkLabel: "Project page",
  },
  // Present in the manuscript evolution tree: IDs 78, 114, 68, and 111.
  {
    id: "liang2023code",
    title: "Code as Policies",
    year: 2023,
    branch: "embodied",
    kind: "System",
    detail:
      "Code as Policies: Language Model Programs for Embodied Control (ICRA 2023)",
    url: "https://code-as-policies.github.io/",
    linkLabel: "Project page",
  },
  {
    id: "shen2023hugginggpt",
    title: "HuggingGPT",
    year: 2023,
    branch: "digital",
    kind: "System",
    detail:
      "HuggingGPT: Solving AI Tasks with ChatGPT and its Friends in Hugging Face (NeurIPS 2023)",
    url: "https://github.com/microsoft/JARVIS",
    linkLabel: "Code repository",
  },
  {
    id: "yang2024safetychip",
    title: "Safety Chip",
    year: 2024,
    branch: "embodied",
    kind: "System",
    detail:
      "Plug in the Safety Chip: Enforcing Constraints for LLM-driven Robot Agents (ICRA 2024)",
    url: "https://yzylmc.github.io/safety-chip/",
    linkLabel: "Project page",
  },
  {
    id: "cheng2024seeclick",
    title: "SeeClick",
    year: 2024,
    branch: "digital",
    kind: "Model",
    detail:
      "SeeClick: Harnessing GUI Grounding for Advanced Visual GUI Agents (ACL 2024)",
    url: "https://github.com/njucckevin/SeeClick",
    linkLabel: "Code repository",
  },
  // Present in the manuscript evolution tree: IDs 6 and 49.
  {
    id: "zhao2026dream",
    title: "Dream.exe",
    year: 2026,
    branch: "robotics",
    kind: "Benchmark",
    detail:
      "Dream.exe: Can Video Generation Models Dream Executable Robot Manipulation?",
    url: "https://github.com/showlab/Dream.exe",
    linkLabel: "Code repository",
  },
  {
    id: "lu2026bench",
    title: "IS-Bench",
    year: 2026,
    branch: "embodied",
    kind: "Benchmark",
    detail:
      "IS-Bench: Evaluating Interactive Safety of VLM-Driven Embodied Agents in Daily Household Tasks (AAAI 2026)",
    url: "https://github.com/AI45Lab/IS-Bench",
    linkLabel: "Code repository",
  },
];
